spring:
  datasource:
    url: jdbc:mysql://${DB_URL}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: ms-project

  security:
    user:
      name: ${USERNAME}
      password: ${USER_PASSWORD}

  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS}
    topic:
      cloud-update-statistics: cloud-update-statistics

    properties:
      ssl.endpoint.identification.algorithm: https
      sasl.mechanism: PLAIN
      request.timeout.ms: 3000
      security.protocol: SASL_SSL
      retry.backoff.ms: 500
      retries: 3
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username='${CLUSTER_API_KEY}' password='${CLUSTER_API_SECRET}';
      max.block.ms: 5000
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        acks: all
        retries: 10000000
        max.in.flight.requests.per.connection: 1
        enable.idempotence: true

server:
  servlet:
    contextPath: /ms-project